config/routes.rb
TwochSummary::Application.routes.draw do
  root 'root#index'
  get "root/blog_site_redirect/:id" => "root#blog_site_redirect", as: :root_blog_site_redirect

  get "/subjects/index/" => "subjects#index", as: :subjects_index
  get "/subjects/feed/" => "subjects#feed"

  get "/subject_rankings/:kind/" => "subject_rankings#index"
  get "/subject_rankings/:kind/:yy/:mm/:dd" => "subject_rankings#index"
  resources :subject_rankings

  get "/blog_rankings/:kind/" => "blog_rankings#index"
  get "/blog_rankings/:kind/:yy/:mm/:dd" => "blog_rankings#index"
  get "/blog_rankings/feed/" => "blog_rankings#feed"
  resources :blog_rankings

end

app/models/blog_ranking.rb
class BlogRanking < ActiveRecord::Base
  belongs_to :blog
  belongs_to :blog_point
  require 'cache/blog_cache'
  include Blog_cache
  require 'cache/blog_point_cache'
  include BlogPoint_cache
  extend Ranking

  KIND_DAY = 0
  KIND_WEEK = 1
  KIND_MONTH = 2

  def self.ranking_class
    BlogRanking
  end

  def self.cache_key_ranking_day
    'blog_ranking:day_ranking:%s'
  end

  def self.cache_key_ranking_week
    'blog_ranking:week_ranking'
  end

  #overwrite, please!
  def self.cache_key_ranking_month
    'blog_ranking:month_ranking'
  end
end

app/controllers/blog_rankings_controller.rb
class BlogRankingsController < ApplicationController
  include RankingsController

  def ranking_class
    BlogRanking
  end

  def index
    @today = Date.today
    @yesterday = Date.today.prev_day
    @rankings = super

    @search_form = SearchForm.new params[:search_form]
    if @search_form.q.present?
      regexp = /#{@search_form.q}/
      rankings = @rankings.select{|ranking|regexp =~ ranking.blog_point.blog.name}
      @rankings = Kaminari.paginate_array(rankings).page(params[:page]).per(30)
    end

    @search_from_path = 'blog_rankings/search_from'
    case params[:kind]
    when 'day','yesterday'
      yy = params[:yy].to_i
      mm = params[:mm].to_i
      dd =  params[:dd].to_i
      date = Date.new(yy,mm,dd)
    when 'week','month'
      date = Date.today
    else
      date = Date.today
    end
    @search_from_params = {:kind => params[:kind], :day => date}

    respond_to do |format|
      format.html
      format.rss
    end
  end
end

app/helpers/blog_rankings_helper.rb
module BlogRankingsHelper
  def blog_ranking_link_to(str, kind, options={})
    target_date = Date.today

    link = ''
    case kind
    when 'today'
      link = "/blog_rankings/day/#{target_date.year}/#{target_date.month}/#{target_date.day}"
    when 'yesterday'
      target_date = target_date.prev_day
      link = "/blog_rankings/day/#{target_date.year}/#{target_date.month}/#{target_date.day}"
    when 'week'
      link = "/blog_rankings/week/"
    when 'month'
      link = "/blog_rankings/month/"
    end

    if options[:class]
      cls = "class = \"#{options[:class]}\""
    end
    if options[:id]
      id = "id = \"#{options[:class]}\""
    end

    return "<a #{cls} #{id} href=\"#{link}\">#{str}</a>".html_safe
  end
end

app/views/blog_rankings/index.html.erb
<h3 class="entry">ブログランキング&nbsp;<a href="/blog_rankings.rss"><%= image_tag "icon/rss.png" %></a></h3>

<table class="table table-striped table-bordered table-condensed">
    <thead>
    </thead>
    <tbody>
        <% @rankings.each do |ranking| %>
        <tr>
        <td class="entry_num">
            <%= ranking.rank %>位&nbsp;<br />
        </td>
        <td class="entry_data">
            <%= link_to ranking.blog_point.blog.name, ranking.blog_point.blog.site_url, :class=>"entry_title", :target=>["_blank"] %><br />
            <span class="entry_point"><%= ranking.blog_point.point %>ポイント</span>
        </td>
        </tr>
        <% end %>
    </tbody>
</table>
<%= paginate @rankings %>

app/views/blog_rankings/search_from.html.erb
<%= form_for @search_form, url: blog_rankings_path, html: {method: :get, class: "navbar-search pull-left"} do |f| %>
    <%= f.search_field :q, :class => "search-query span2", :placeholder => "Search"%>
    <%= f.hidden_field :kind, {:name=>'kind', :value => @search_from_params[:kind]} %>
    <%= f.hidden_field :yy, {:name=>'yy', :value => @search_from_params[:day].year} %>
    <%= f.hidden_field :mm, {:name=>'mm', :value => @search_from_params[:day].month} %>
    <%= f.hidden_field :dd, {:name=>'dd', :value => @search_from_params[:day].day} %>
<% end %>

app/views/blog_rankings/show.html.erb
<h1>show#index</h1>

<% @rankings.each do |ranking| %>
	<div class='blog'>
		rank:<%= ranking.rank %>
		point:<%= ranking.point %>
		<%= link_to ranking.blog.name, ranking.blog.site_url, :target=>["_blank"] %>
	</div>
<% end %>