config/routes.rb
TwochSummary::Application.routes.draw do
  root 'root#index'
  get "root/blog_site_redirect/:id" => "root#blog_site_redirect", as: :root_blog_site_redirect

  get "/subjects/index/" => "subjects#index", as: :subjects_index
  get "/subjects/feed/" => "subjects#feed"

  get "/subject_rankings/:kind/" => "subject_rankings#index"
  get "/subject_rankings/:kind/:yy/:mm/:dd" => "subject_rankings#index"
  resources :subject_rankings

  get "/blog_rankings/:kind/" => "blog_rankings#index"
  get "/blog_rankings/:kind/:yy/:mm/:dd" => "blog_rankings#index"
  get "/blog_rankings/feed/" => "blog_rankings#feed"
  resources :blog_rankings

end

app/models/subject_ranking.rb
class SubjectRanking < ActiveRecord::Base
  belongs_to :subject
  belongs_to :subject_point
  require 'cache/subject_cache'
  include Subject_cache
  require 'cache/subject_point_cache'
  include SubjectPoint_cache
  extend Ranking

  KIND_DAY = 0
  KIND_WEEK = 1
  KIND_MONTH = 2

  def self.ranking_class
    SubjectRanking
  end

  def self.cache_key_ranking_day
    'subject_ranking:day_ranking:%s'
  end

  def self.cache_key_ranking_week
    #'subject_ranking:week_ranking:%s'
    'subject_ranking:week_ranking'
  end

  #overwrite, please!
  def self.cache_key_ranking_month
    #'subject_ranking:month_ranking:%s'
    'subject_ranking:month_ranking'
  end
end

app/controllers/subject_rankings_controller.rb
class SubjectRankingsController < ApplicationController
  include RankingsController

  def ranking_class
    SubjectRanking
  end

  def index
    @today = Date.today
    @yesterday = Date.today.prev_day
    @rankings = super

    @search_form = SearchForm.new params[:search_form]
    if @search_form.q.present?
      regexp = /#{@search_form.q}/
      rankings = @rankings.select{|ranking|regexp =~ ranking.subject_point.subject.title}
      @rankings = Kaminari.paginate_array(rankings).page(params[:page]).per(30)
    end

    @search_from_path = 'subject_rankings/search_from'
    case params[:kind]
    when 'day','yesterday'
      yy = params[:yy].to_i
      mm = params[:mm].to_i
      dd =  params[:dd].to_i
      date = Date.new(yy,mm,dd)
    when 'week','month'
      date = Date.today
    else
      date = Date.today
    end
    @search_from_params = {:kind => params[:kind], :day => date}

    respond_to do |format|
      format.html
      format.rss
    end
  end
end

app/helpers/subject_rankings_helper.rb
module SubjectRankingsHelper
  def subject_ranking_link_to(str, kind, options={})
    target_date = Date.today

    link = ''
    case kind
    when 'today'
      link = "/subject_rankings/day/#{target_date.year}/#{target_date.month}/#{target_date.day}"
    when 'yesterday'
      target_date = target_date.prev_day
      link = "/subject_rankings/day/#{target_date.year}/#{target_date.month}/#{target_date.day}"
    when 'week'
      link = "/subject_rankings/week/"
    when 'month'
      link = "/subject_rankings/month/"
    end

    if options[:class]
      cls = "class = \"#{options[:class]}\""
    end
    if options[:id]
      id = "id = \"#{options[:class]}\""
    end

    return "<a #{cls} #{id} href=\"#{link}\">#{str}</a>".html_safe
  end
end

app/views/subject_rankings/index.html.erb
<h3 class="entry">記事ランキング&nbsp;<a href="/subject_rankings.rss"><%= image_tag "icon/rss.png" %></a></h3>

<table class="table table-striped table-bordered table-condensed">
    <thead>
    </thead>
    <tbody>
        <% @rankings.each do |ranking| %>
        <tr>
        <td class="entry_num">
            <%= ranking.rank %>位&nbsp;<br />
        </td>
        <td class="entry_data">
            <%= ranking.subject_point.point %>ポイント
            <%= link_to ranking.subject_point.subject.title, ranking.subject_point.subject.site_url, :class=>"entry_title", :target=>["_blank"] %><br />
            <%= link_to ranking.subject_point.subject.blog.name, ranking.subject_point.subject.blog.site_url, :class=>"entry_site", :target=>["_blank"] %>
        </td>
        </tr>
        <% end %>
    </tbody>
</table>
<%= paginate @rankings %>

app/views/subject_rankings/search_from.html.erb
<%= form_for @search_form, url: subject_rankings_path, html: {method: :get, class: "navbar-search pull-left"} do |f| %>
    <%= f.search_field :q, :class => "search-query span2", :placeholder => "Search"%>
    <%= f.hidden_field :kind, {:name=>'kind', :value => @search_from_params[:kind]} %>
    <%= f.hidden_field :yy, {:name=>'yy', :value => @search_from_params[:day].year} %>
    <%= f.hidden_field :mm, {:name=>'mm', :value => @search_from_params[:day].month} %>
    <%= f.hidden_field :dd, {:name=>'dd', :value => @search_from_params[:day].day} %>
<% end %>

app/views/subject_rankings/show.html.erb
<h1>show#index</h1>

<% @rankings.each do |ranking| %>
	<div class='subject'>
		rank:<%= ranking.rank %>
		point:<%= ranking.point %>
		<%= link_to ranking.subject.title, ranking.subject.site_url, :target=>["_blank"] %>
		<%= ranking.subject.content[0..100] %>
	</div>
<% end %>