config/routes.rb
TwochSummary::Application.routes.draw do
  root 'root#index'
  get "root/blog_site_redirect/:id" => "root#blog_site_redirect", as: :root_blog_site_redirect

  get "/subjects/index/" => "subjects#index", as: :subjects_index
  get "/subjects/feed/" => "subjects#feed"

  get "/subject_rankings/:kind/" => "subject_rankings#index"
  get "/subject_rankings/:kind/:yy/:mm/:dd" => "subject_rankings#index"
  resources :subject_rankings

  get "/blog_rankings/:kind/" => "blog_rankings#index"
  get "/blog_rankings/:kind/:yy/:mm/:dd" => "blog_rankings#index"
  get "/blog_rankings/feed/" => "blog_rankings#feed"
  resources :blog_rankings

end

app/controllers/root_controller.rb
class RootController < ApplicationController
    def index
        @subjects = Subject.latest(10)
        @today = Date.today
        @blog_rankings = BlogRanking.day_ranking(@today)
        @subject_rankings = SubjectRanking.day_ranking(@today)
        @yesterday = Date.today.prev_day
        @yesterday_blog_rankings = BlogRanking.day_ranking(@yesterday)
        @yesterday_subject_rankings = SubjectRanking.day_ranking(@yesterday)

        # 昨日から1週間、1ヶ月分
        # 本日分は変化が激しいので、固定しておきたい
        @week_blog_rankings = BlogRanking.week_ranking
        @week_subject_rankings = SubjectRanking.week_ranking
        @month_blog_rankings = BlogRanking.month_ranking
        @month_subject_rankings = SubjectRanking.month_ranking

        @search_from_path = 'root/search_from'
        @search_form = SearchForm.new params[:search_form]
        if @search_form.q.present?
          @subjects = @subjects.where("title like '%#{@search_form.q}%'")
        end
    end

    def blog_site_redirect
        # subjectのsite_urlにリダイレクトさせてランキングのポイントを更新させる
        subject = Subject.find(:first, :conditions => ["id = ?", params[:id]])

        if subject.blank?
            redirect_to "/"
        else
            BlogPoint.update_point(subject)
            SubjectPoint.update_point(subject)

            redirect_to "#{subject.site_url}"
        end
    end
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/root/_ranking_blog.html.erb
<% if blog_rankings.size  == 0 then %>
    ランキング集計中です
<% else  %>
<table class="table table-striped table-bordered table-condensed">
    <thead>
    </thead>
    <tbody>
        <% blog_rankings[0..9].each do |ranking| %>
        <tr>
        <td class="entry_num">
            <%= ranking.rank %>位&nbsp;<br />
        </td>
        <td class="entry_data">
            <%= link_to ranking.blog_point.blog.name, ranking.blog_point.blog.site_url, :class=>"entry_title", :target=>["_blank"] %><br />
            <span class="entry_point"><%= ranking.blog_point.point %>ポイント</span>
        </td>
        </tr>
        <% end %>
    </tbody>
</table>
<div align="right">
    <%= blog_ranking_link_to '続きを見る', target_date, :class => 'btn' %>
</div>
<% end %>

app/views/root/_ranking_subject.html.erb
<% if subject_rankings.size  == 0 then %>
    ランキング集計中です
<% else  %>
<table class="table table-striped table-bordered table-condensed">
    <thead>
    </thead>
    <tbody>
        <% subject_rankings[0..9].each do |ranking| %>
        <td class="entry_num">
            <%= ranking.rank %>位&nbsp;<br />
        </td>
        <td class="entry_data">
            <%= link_to ranking.subject_point.subject.title, ranking.subject_point.subject.site_url, :class=>"entry_title", :target=>["_blank"] %><br />
            <span class="entry_point"><%= ranking.subject_point.point %>ポイント</span>
            <%= link_to ranking.subject_point.subject.blog.name, ranking.subject_point.subject.blog.site_url, :class=>"entry_site", :target=>["_blank"] %>
        </td>
        </tr>
        <% end %>
    </tbody>
</table>
<div align="right">
    <%= subject_ranking_link_to '続きを見る', target_date, :class => 'btn' %>
</div>
<% end  %>

app/views/root/index.html.erb
<h3 class="entry">新着一覧&nbsp;<a href="/subjects/feed.rss"><%= image_tag "icon/rss.png" %></a></h3>
<table class="table table-striped table-bordered table-condensed">
    <thead>
    </thead>
    <tbody>
    <% @subjects[0..9].each do |subject| %>
        <tr><td>
            <%= link_to subject.title, root_blog_site_redirect_path(subject), :class=>"entry_title", :target=>["_blank"] %><br />
            <%= link_to subject.blog.name, subject.blog.site_url, :class=>"entry_site", :target=>["_blank"] %>
            <span class="entry_time"><%= subject.created_at.strftime("%H:%m")%> </span>
        </td></tr>
    <% end %>
    </tbody>
</table>
<div align="right">
    <a class="btn" href=<%= subjects_index_path(:page => 1) %>>続きを見る</a>
</div>

<h3 class="entry">記事ランキング&nbsp;<a href="/subject_rankings.rss"><%= image_tag "icon/rss.png" %></a></h3>
<div class="tabbable">
    <ul class="nav nav-tabs" id="subject_tab">
        <li class="active"><a href="#tab1" data-jitoggle="tab">今日</a></li>
        <li><a href="#tab2" data-toggle="tab">昨日</a></li>
        <li><a href="#tab3" data-toggle="tab">週間</a></li>
        <li><a href="#tab4" data-toggle="tab">月間</a></li>
    </ul>
    <div id="subject-tab-content" class="tab-content">
        <div class="tab-pane active" id="tab1">
            <%= render :partial => "root/ranking_subject", :locals => {:subject_rankings => @subject_rankings, :target_date => "today"} %>
        </div>
        <div class="tab-pane" id="tab2">
            <%= render :partial => "root/ranking_subject", :locals => {:subject_rankings => @yesterday_subject_rankings, :target_date => "yesterday"} %>
        </div>
        <div class="tab-pane" id="tab3">
            <%= render :partial => "root/ranking_subject", :locals => {:subject_rankings => @week_subject_rankings, :target_date => "week"} %>
        </div>
        <div class="tab-pane" id="tab4">
            <%= render :partial => "root/ranking_subject", :locals => {:subject_rankings => @month_subject_rankings, :target_date => "month"} %>
        </div>
    </div>
</div>

<h3 class="entry">ブログランキング&nbsp;<a href="/blog_rankings.rss"><%= image_tag "icon/rss.png" %></a></h3>
<div class="tabbable">
    <ul class="nav nav-tabs" id="blog_tab">
        <li class="active"><a href="#blog_tab1" data-jitoggle="tab">今日</a></li>
        <li><a href="#blog_tab2" data-toggle="tab">昨日</a></li>
        <li><a href="#blog_tab3" data-toggle="tab">週間</a></li>
        <li><a href="#blog_tab4" data-toggle="tab">月間</a></li>
    </ul>
    <div id="subject-tab-content" class="tab-content">
        <div class="tab-pane active" id="blog_tab1">
            <%= render :partial => "root/ranking_blog", :locals => {:blog_rankings => @blog_rankings, :target_date => "today"} %>
        </div>
        <div class="tab-pane" id="blog_tab2">
            <%= render :partial => "root/ranking_blog", :locals => {:blog_rankings => @yesterday_blog_rankings, :target_date => "yesterday"} %>
        </div>
        <div class="tab-pane" id="blog_tab3">
            <%= render :partial => "root/ranking_blog", :locals => {:blog_rankings => @week_blog_rankings, :target_date => "week"} %>
        </div>
        <div class="tab-pane" id="blog_tab4">
            <%= render :partial => "root/ranking_blog", :locals => {:blog_rankings => @month_blog_rankings, :target_date => "month"} %>
        </div>
    </div>
</div>

app/views/root/index_mobile.html.erb
テスト
テスト

app/views/root/index_smart_phone.html.erb
spテスト

app/views/root/search_from.html.erb
<%= form_for @search_form, url: subjects_index_path, html: {method: :get, class: "navbar-search pull-left"} do |f| %>
    <%= f.search_field :q, :class => "search-query span2", :placeholder => "Search"%>
<% end %>